AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  prompt-lib-api

  Sample SAM Template for prompt-lib-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: python3.12
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  PromptLibApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title:
            Ref: AWS::StackName
        paths:
          /prompts:
            get:
              produces:
                - application/json
              responses:
                "200":
                  description: "200 response"
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetPromptsFunction.Arn}/invocations
                responses: {}
                httpMethod: POST
                type: aws_proxy
  GetPromptsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/getPrompts/
      Environment:
        Variables:
          DB_DATABASE: postgres
          DB_HOST: localhost
          DB_PASSWORD: postgres
          DB_PORT: "5434"
          DB_USER: postgres
      Handler: app.lambda_handler
      Layers:
        - !Ref MySharedLibsLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref PromptLibApi
            Path: /prompts
            Method: get
  MySharedLibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: my-shared-libs
      Description: Shared libraries for Lambda functions
      ContentUri: src/libs/
      CompatibleRuntimes:
        - python3.12
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.12
